text = "Hi My name is Guptaeen"
print(text.upper())
print(text.lower())
print(text.istitle())
print(text.count('i'))
print(text.find('guptaeen'))
print(text.startswith("Hi"))
print(text.endswith("gupateen"))
print(text.split())
print('Hi' in text)
print('Hello' not in text)